# Build by JDM-Buildozer
name: JDM_template
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build APK
              uses: digreatbrian/buildozer-action@v1
              with:
                  buildozer-cmd: buildozer -v android debug
                  work-dir: .

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: JDM_template-0.0.1
                  path: ./bin/*.apk
# Build by JDM-Buildozer
# name: JDM_template
# on: workflow_dispatch

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2

#             - name: Install dependencies
#               run: |
#                   sudo apt update
#                   sudo apt install -y autoconf automake autopoint build-essential ccache cmake gettext git libffi-dev libltdl-dev libssl-dev liblzma-dev libtool openjdk-8-jdk patch pkg-config python3-pip python3-setuptools sudo unzip zip zlib1g-dev

#             - name: Build APK
#               uses: digreatbrian/buildozer-action@v1
#               with:
#                   buildozer-cmd: buildozer -v android debug
#                   work-dir: .

#             - name: Upload artifacts
#               uses: actions/upload-artifact@v3
#               with:
#                   name: JDM_template-0.0.1
#                   path: ./bin/*.apk
